theme: null
title: Therapets Manual
description: Documentación oficial y visión del sistema Therapets.
# Variables para la navegación global
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
